### ISSUE TITLE
[Suggestion] Don't show level in sandbox mode

### ISSUE THREAD

**Issue by tyrope** [DMagic1/KSP-Portrait-Stats#1]
Since, in sandbox mode, all Kerbals automatically get Lvl5 when they spawn in their first mission the stars are kind of superfluous. Knowing whether or not it's a Pilot is still useful for SAS, however. As is knowing if a Kerbal is an engineer for other mods (KIS comes to mind)

**Comment by DMagic1** [comment]
That's a good idea, and simple to do. Though I assume you mean don't show levels in sandbox mode.

Does science mode also start all Kerbals at level 5, or is it only sandbox?

**Comment by tyrope** [comment]
I'm a silly that tells people the exact opposite of what he means. but yes, sandbox mode. unsure about science mode.

**Comment by tyrope** [comment]
Science mode also gives Kerbals 5 stars upon hire, making this only needed in career mode.

**Comment by DMagic1** [comment]
Fixed in version 4.
